"""Real PostgreSQL CHECK comparison must ignore only dialect spelling differences."""

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import inspect, text

from tests.integration.test_persistence_postgres import migration_config
from tests.integration.test_persistence_postgres import postgres_engine as _postgres_engine

pytestmark = pytest.mark.integration
postgres_engine = _postgres_engine


@pytest.mark.parametrize("drift", ["missing", "extra"])
def test_check_comparison_detects_real_drift(postgres_engine, drift):
    with postgres_engine.begin() as connection:
        config = migration_config(connection)
        command.check(config)
        table = "resource_relationship_observations"
        constraints = inspect(connection).get_check_constraints(table)
        original = next(c for c in constraints if "collector_version" in c["name"])
        quote = connection.dialect.identifier_preparer.quote
        if drift == "missing":
            connection.execute(
                text(f"ALTER TABLE {table} DROP CONSTRAINT {quote(original['name'])}")
            )
        else:
            connection.execute(
                text(f"ALTER TABLE {table} ADD CONSTRAINT ck_extra_fixture CHECK (1 = 1)")
            )
        with pytest.raises(AutogenerateDiffsDetected):
            command.check(config)
        if drift == "missing":
            connection.execute(
                text(
                    f"ALTER TABLE {table} ADD CONSTRAINT {quote(original['name'])} "
                    f"CHECK ({original['sqltext']})"
                )
            )
        else:
            connection.execute(text(f"ALTER TABLE {table} DROP CONSTRAINT ck_extra_fixture"))
        command.check(config)
